### ISSUE TITLE
Meta: Redesign site desktop

### ISSUE THREAD

**Issue by amitaibu** [Gizra/Gizra#195]
* [x] Homepage (#196)
* [x] Blog posts teaser (#202)
* [x] Single blog post (#198)
* [x] Team page (#200)
* [x] About story page (#213)

https://www.dropbox.com/sh/0t7nsx3i9vznqx3/AACyulEAl7BnwgySy3aJt5Z1a?dl=0

**Comment by YuriGizra** [comment]
@kerensoref, 
Hi, could you, please, make wix logo on transparent background:
![wix](https://cloud.githubusercontent.com/assets/7760669/11092556/0080da0c-888d-11e5-84c7-b435fbe10013.png)
Thanks.

**Comment by YuriGizra** [comment]
@amitaibu, 
Is this carousel?
![selection_341](https://cloud.githubusercontent.com/assets/7760669/11096357/47e2fb4a-88a2-11e5-9088-58393106d34e.jpg)

**Comment by amitaibu** [comment]
Yes

**Comment by kerensoref** [comment]
The wix logo is updated in the home page psd

**Comment by YuriGizra** [comment]
@kerensoref 
Hi, could you, please, add Acquia logo on transparent background:
![acquia 2498](https://cloud.githubusercontent.com/assets/7760669/11211550/dc533412-8d38-11e5-920c-ca41615cca56.png)

Thanks.

**Comment by YuriGizra** [comment]
@kerensoref ,
Hi, could you, please, resize the design to 1336px include gaps:
![selection_370](https://cloud.githubusercontent.com/assets/7760669/11212572/49a7c32e-8d3f-11e5-9f6a-6761d574e48d.jpg)

Thanks.

**Comment by kerensoref** [comment]
https://www.dropbox.com/s/8qmxmm4bu3gqdys/final%20fp1366.psd?dl=0

**Comment by YuriGizra** [comment]
@kerensoref, @amitaibu 
The file has 1366px width, we need reduce 30px to 1336px. Becouse browsers have scroll element and some of them borders. To avoid horizontal  scroll in full screen (1366px) we need reduce width by 30px.

**Comment by kerensoref** [comment]
Updated in Dropbox

**Comment by YuriGizra** [comment]
@kerensoref,
Thanks.

**Comment by YuriGizra** [comment]
@kerensoref, it is still 1366px.
![selection_376](https://cloud.githubusercontent.com/assets/7760669/11269844/850d4572-8ec2-11e5-82f5-c18c11d89fa1.jpg)

**Comment by kerensoref** [comment]
It was probably still uploading. Try now...

**Comment by YuriGizra** [comment]
@kerensoref 
Thanks,  it's properly now.

**Comment by YuriGizra** [comment]
@kerensoref,

the Verdana font (bold) in design:
![selection_386](https://cloud.githubusercontent.com/assets/7760669/11336992/2ad7b7c6-91f2-11e5-9aa1-71bc1413e1b8.jpg)

Doesn't look like in web:
![selection_385](https://cloud.githubusercontent.com/assets/7760669/11337029/726a003a-91f2-11e5-861d-dee970fe88a6.jpg)

We should chenge it or its normal?

**Comment by kerensoref** [comment]
Can we use Helvetica instead?

**Comment by YuriGizra** [comment]
@kerensoref 
This is helvetica bold:
![selection_391](https://cloud.githubusercontent.com/assets/7760669/11363883/423099c0-92a5-11e5-86ef-69b601f15188.jpg)

Is this OK?

**Comment by kerensoref** [comment]
Looks good.. can it be lighter?

**Comment by YuriGizra** [comment]
no. only bold or regular:
![selection_394](https://cloud.githubusercontent.com/assets/7760669/11367952/aa9ea848-92bf-11e5-9ce2-64d3fd6dd963.jpg)

**Comment by kerensoref** [comment]
OK. So let's use it as is.
